services:
  backend:
    build: ./mdd-hqc-backend
    container_name: mdd-hqc-backend
    ports:
      - "8000:8000"
    volumes:
      - ./mdd-hqc-backend/app:/app/app
      - ./mdd-hqc-backend/data:/app/data
    environment:
      - OPENROUTER_API_KEY=api_key_aqui
    networks:
      - appnet

  frontend:
    build: ./mdd-hqc-frontend
    container_name: mdd-hqc-frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./mdd-hqc-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge